name: pm_prototype
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  core:
    path: core
  sidebarx: ^0.17.1
  go_router: ^14.2.3
  data_table_2: ^2.5.15
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  meta: ^1.15.0
  bloc: ^8.1.4
  lottie: ^3.1.3
  appwrite: ^13.0.0
  get_it: ^8.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
